apiVersion: apps/v1
kind: Deployment
metadata:
  name: siem-api
spec:
  selector:
    matchLabels:
      app: siem-api
  replicas: 1
  template:
    metadata:
      labels:
        app: siem-api
    spec:
      imagePullSecrets:
        - name: aws-ecr
      containers:
      - name: siem-api
        image: 543300470803.dkr.ecr.ap-southeast-1.amazonaws.com/siem_api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: siem-api
  name: siem-api
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: siem-api
  type: ClusterIP
